### ISSUE TITLE
GZIP compression is not working

### ISSUE THREAD

**Issue by kucharzyk** [shardis/spring-angular2-starter#35]
It looks like GZIP compression is not working properly.

It's configured for tomcat but it's not working for some reason

```
# EMBEDDED SERVER CONFIGURATION
server:
    compression:
      enabled: true
      min-response-size: 1024
      mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json
```
